### ISSUE TITLE
Calendario - Eventos y Recordatorios

### ISSUE THREAD

**Issue by torehc** [andensinlimite/metaespacio#11]
Conectar Django con la API de Google Calendar para los eventos de los espacio y recordatorios de fecha de pago, etc...

**Comment by torehc** [comment]
En primer lugar incrustar HTML de calendario compartido de Google en la web.
Se plantea realizar las notificaciones con los usuarios mediante Telegram (En investigación)

**Comment by enen** [comment]
LA semana pasada se incrustó un calendario de eventos en el espacio de AndenSinLímite. Se propone mezclarlo con el de organización de la apertura.

**Comment by enen** [comment]
Se ha hecho pública, junto con el calendario de eventos, el calendario de apertura del anden en http://anden.metaespacio.org/eventos
