### ISSUE TITLE
Vista por mes

### ISSUE THREAD

**Issue by torehc** [andensinlimite/metaespacio#4]
En "cuotas/mensualidades/<user>" separar la tabla por meses y hacer una suma total de lo aportado por mes. 
Con esos datos de aportación mensual generar una gráfica con la aportación personal.

**Comment by amd77** [comment]
Se propone dejar esta vista y crear una nueva que podria ser cuotas/mensualidades/2015/ donde se vea esa tabla y esa grafica, ya que la actual puede ser util para ver el desglose.

**Comment by enen** [comment]
http://www.highcharts.com/demo/bar-stacked/grid-light

Librería JS propuesta por torehc y formato de gráfica como sugerencia personal para clasificar los distintos métodos de pago (diferentes colores) clasificados por mes (cada barra) para cada usuario (su propia gráfica) y opcionalmente emplear la herramienta para otras gráficas que nos interesen

**Comment by torehc** [comment]
Muy factible utilizar:
https://github.com/agiliq/django-graphos
http://agiliq.com/demo/graphos/

**Comment by enen** [comment]
Completada la gráfica en la rama develop en el commit 985e67ebf2fe586fe1bb869d6f6270564978b23a
