### ISSUE TITLE
Usuarios No Socio sin mensajes

### ISSUE THREAD

**Issue by torehc** [andensinlimite/metaespacio#6]
A los usuarios que "No son Socios" no les aparece ningún mensaje diciendo que están en ese estado ni tampoco la parte en la que dicen que están logeados en el sistema y donde está el "sing out".

**Comment by enen** [comment]
Las opciones de que estén loguedos o no, y como salir, se muestran en el menú verde (Mi cuenta) en la zona superior derecha, debajo de la barra de menús oscura.
