### ISSUE TITLE
Socio sin menú de usuario

### ISSUE THREAD

**Issue by torehc** [andensinlimite/metaespacio#7]
Al estar un usuario normal (es socio) ya logeado no le aparece el menú con los datos de usuario. 
(_menu_user.html).
Por lo que no puede ver o modificar sus datos personales o cerrar sesión.

**Comment by enen** [comment]
@amd77 ya debió resolver este bug porque yo puedo ver el menú del user y admin de la demo.json sin problemas. También con socios y no socios.

**Comment by amd77** [comment]
Creo que fue que lo de los sites no estaba correcto, y al tener el site_id=1 estaba yendo al de example.com, del cual el usuario no es miembro. Vamos, un lio.
